id: I43EFF1FE
legacy_id: P000755
ocr_import_info:
  bdrc_scan_id: W23637
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T13:05:00'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:27:05.945200+00:00'
last_modified: 2022-09-02 09:29:02.612447
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23637
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23637
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན་གྱི་གསུང་སྐོར།
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
statistics:
  ocr_word_mean_confidence_index: 0.9270196455564992
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG12195:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12195
      total_pages: 532
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG12195.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9315718822680633
    legacy_id: v003
  I3597:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3597
      total_pages: 576
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3597.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9419364808018722
    legacy_id: v001
  I3598:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3598
      total_pages: 672
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3598.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9117988751289902
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
