id: I43EFF1FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T13:08:42+00:00'
last_modified: '2022-06-07T13:38:38.084652+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23637
  title: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན་གྱི་གསུང་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    71C8:
      image_group_id: I3597
      title: ''
      total_pages: 576
      order: 1
      base_file: 71C8.txt
    FB5E:
      image_group_id: I3598
      title: ''
      total_pages: 672
      order: 2
      base_file: FB5E.txt
    '7146':
      image_group_id: I1KG12195
      title: ''
      total_pages: 532
      order: 3
      base_file: 7146.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
